### ISSUE TITLE
Add device acknowledgement for identified webapp commands

### ISSUE THREAD

**Issue by mechawrench** [mechawrench/wificom-lib#27]
It would be ideal for commands from the web app to notify the web app server that the commands were successfully received and processed.  This would give more accurate data on the web app success/error message output.

See related issue https://github.com/mechawrench/wificom-webapp/issues/5

**Comment by mechawrench** [comment]
This has been added to develop and is also live on the QA version of the website.

**Comment by dmcomm** [comment]
Do I understand right we deliberately don't have any error messages yet?

**Comment by mechawrench** [comment]
Right, I haven't added it yet, can probably do so easily - I'll look
into this soon

On November 12, 2022, GitHub ***@***.***> wrote:
> Do I understand right we deliberately don't have any error messages
> yet?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/mechawrench/wificom-lib/issues/27#issuecomment-
1312611659>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AB2IL356J5XHE4SOGUVWIX3WIA7YDANCNFSM6AAAAAARXYFCW4>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by dmcomm** [comment]
Done in f02b5d6
