### ISSUE TITLE
Sometimes becomes unresponsive when switching RTB mode/role

### ISSUE THREAD

**Issue by dmcomm** [mechawrench/wificom-lib#33]
Not sure if it's a particular sequence of events or if it's intermittent. More investigation needed.

**Comment by mechawrench** [comment]
I've also seen this but it was able to recover after a short wait (20s?), seemed to impact both nina and picow for me

**Comment by dmcomm** [comment]
Tried to test this and still confused.

Changing from PenX host to guest forgot to dim the LED (though it still works), but I think that's a different thing.

**Comment by dmcomm** [comment]
It's also not reliable about accepting a new digirom after using a Legendz digirom. Probably the same thing.

**Comment by dmcomm** [comment]
This seems better recently?

**Comment by dmcomm** [comment]
I've not had a problem with it recently.
