### ISSUE TITLE
Handle exceptions better

### ISSUE THREAD

**Issue by dmcomm** [mechawrench/wificom-lib#37]
We should be noting which ones come up where, so we can decide what to do about each one.

**Comment by dmcomm** [comment]
Catch MQTT exceptions and count them? What causes them? Can we reproduce?

**Comment by dmcomm** [comment]
#58 and #67 handle the ones at startup, which are by far the most common, but we should still look at the ones that happen later.

**Comment by mechawrench** [comment]
Added PR #73 to address MQTT intermittent failures

**Comment by dmcomm** [comment]
Testing #73 and my own similar attempt, it seems CircuitPython WiFi has some retry ability built in already, and we don't tend to recover from these network errors, so ignoring them temporarily just prolongs the misery.

**Comment by dmcomm** [comment]
See #114
