### ISSUE TITLE
Create action for release zip with bundled libs

### ISSUE THREAD

**Issue by dmcomm** [mechawrench/wificom-lib#46]
And decide how to handle credits / license info.

**Comment by dmcomm** [comment]
Need a way to specify versions of libs.

**Comment by mechawrench** [comment]
See https://github.com/mechawrench/wificom-lib/pull/50

This PR will do the following:
- Adds "sources.json" as a file to specify what versions of libraries we want, this is parsed by the action
- Downloads specified versions of libraries and puts them in the appropriate place
- Zips up the archive
- Adds the archive to the build artifacts
- If a release is tagged, when running, it will use the tag version as the affixed value on the name

This action is set to run on all pushes, pulls, and releases.  I find value in the artifacts being available for each of these events, with no additional cost to us.
