### ISSUE TITLE
Resolve crash when switching from a mode, then back into Wifi mode

### ISSUE THREAD

**Issue by mechawrench** [mechawrench/wificom-lib#47]
Currently there is a crash when switching from a mode (i.e serial) and then back into WiFi.  This crash occurs nearly instantly when selecting Wifi mode.

Crash logs:

> 18:23:05.439 -> t
> 18:23:15.441 -> t
> 18:23:25.418 -> t
> 18:23:35.434 -> t
> 18:23:45.428 -> t
> 18:23:46.679 -> Running WiFi
> 18:23:46.750 -> Free memory before WiFi: 33584
> 18:23:46.825 -> Connecting to WiFi network [WIFI_SSID]...
> 18:23:46.862 -> Connecting to MQTT Broker...
> 18:23:47.012 -> Traceback (most recent call last):
> 18:23:47.012 ->   File "code.py", line 375, in <module>
> 18:23:47.012 ->   File "code.py", line 111, in main_menu
> 18:23:47.012 ->   File "code.py", line 118, in menu_wifi
> 18:23:47.012 ->   File "code.py", line 185, in run_wifi
> 18:23:47.012 ->   File "/lib/wificom/mqtt.py", line 45, in connect_to_mqtt
> 18:23:47.012 ->   File "adafruit_minimqtt/adafruit_minimqtt.py", line 471, in connect
> 18:23:47.012 ->   File "adafruit_minimqtt/adafruit_minimqtt.py", line 283, in _get_connect_socket
> 18:23:47.012 -> MemoryError:

**Comment by dmcomm** [comment]
Remaining issues should be resolved by #58
