### ISSUE TITLE
Add more audio feedback

### ISSUE THREAD

**Issue by dmcomm** [mechawrench/wificom-lib#52]
Play a particular sound when:
* Starting up
* MQTT connected
* Digirom received from server
* Rebooting after button press

**Comment by mechawrench** [comment]
Would like to bump this up in priority.  The "Digirom received from server" in specific is very useful for testing, and users knowing when to scan.

**Comment by dmcomm** [comment]
"Digirom received from server" added in #70

**Comment by dmcomm** [comment]
Should probably beep on press-to-reboot, but easier to sort out after #108 #110.

**Comment by dmcomm** [comment]
"Starting up" and "MQTT connected" done in #110.
