### ISSUE TITLE
Add version check in serial mode

### ISSUE THREAD

**Issue by dmcomm** [mechawrench/wificom-lib#56]
https://github.com/dmcomm/dmcomm-project/commit/3f555850a11d96072298b84671c0176f2626cee5
https://github.com/dmcomm/dmcomm-python/commit/ed5c1d1b6eddb3d446b9b5917817eba23de57f5b

Want something clever with the CI (autogenerate + commit ID) or will something like the above be good enough? It is admittedly another place to remember to change it.

**Comment by mechawrench** [comment]
Can certainly look into doing this with an action and commit ID
